name: basics
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-47.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  intl_phone_number_input: ^0.7.0+2
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  meta: ^1.15.0
  url_launcher: ^6.3.0

  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/sos.png
